### ISSUE TITLE
calling read(), or write() on 

### ISSUE THREAD

**Issue by raymondxie** [tejashah88/node-wio-link#1]
I am trying to light up a light strip as:
wioClient.node.write(nodeToken, 'GroveLedWs2812D0', 'clear', '32', '880000')

but got the following error:
TypeError: arguments.splice is not a function
    at Object.write (/PATH/PROJ/node_modules/node-wio-link/index.js:73:110)

In general it has problem with "arguments.splice", same issue with "wioClient.node.read()".

**Comment by tejashah88** [comment]
Whoops, that was a mistake on my part. I just patched it in version v0.0.2. Let me know if you run into any other issues.

**Comment by raymondxie** [comment]
Thank you for the quick fix
