### ISSUE TITLE
POST to light change to Ws2812 light strip

### ISSUE THREAD

**Issue by raymondxie** [tejashah88/node-wio-link#2]
It seems that https://us.wio.seeed.io/v1/node/....  does not like application/json post request, when change/set value to OUTPUT device.

For example, if I want to set LED strip color with a post request:
node/GroveLedWs2812D0/clear/20/00FF00
It would error out as: { error: 'Can not accept application/json post request.' }

The fix is to add another header to your index.js file, line 21, such as:
'Content-Type': 'application/x-www-form-urlencoded',
then it would get around the problem.

**Comment by tejashah88** [comment]
That would actually just replace the "Content-Type" to "application/x-www-form-urlencoded". Can you verify that this problem exists with any other Grove modules?

**Comment by raymondxie** [comment]
It seems that wio-iot cloud takes parameters in "path" format, instead of JSON payload. I tried LED light, buzzer, etc, and they works "application/x-www-form-urlencoded", but I could not test all of their OUTPUT devices. 

Also I noticed that the arrow function has problem:
write: (nodeToken, groveInstName, PMA) => rest.post(nodeToken, `node/${groveInstName}/${PMA}/${Object.values(arguments).splice(3).join('/')}`),

The arguments won't capture the "...variable arguments". This fix would work:
     write: function (nodeToken, groveInstName, PMA) {
         console.log( Object.values(arguments) );
         return rest.post(nodeToken, `node/${groveInstName}/${PMA}/${Object.values(arguments).splice(3).join('/')}`)},

**Comment by tejashah88** [comment]
I actually found the [source code](https://github.com/Seeed-Studio/Wio_Link/blob/2574236b054bcebcc42a0708e54f47c65b8fed12/handlers.py) for the REST API and if you search for "json" (including the quotes), there does seem to be an explicit requirement for the "Content-Type" header to be a specific header. I'll make the required changes and post another update for this library.

**Comment by tejashah88** [comment]
Just published a patch for fixing the two aforementioned bugs. LMK how that goes!
